const ORDER_SOURCES = [
  {
    id: 1,
    name: 'Інше',
    alias: 'inse',
    driver: 'other',
    source_name: null,
    source_uuid: null,
    currency_code: 'UAH',
    statuses_toggle: [],
    distribute_by: [],
    expense_type_id: null,
    with_expenses: false,
    send_tracking_code: false,
    statuses_tracking_code: [],
    created_at: '2024-05-08T08:06:05.000000Z',
    updated_at: '2024-05-22T14:16:19.000000Z',
    deleted_at: null,
    shop_info: [],
  },
  {
    id: 2,
    name: 'Ніка',
    alias: 'nika',
    driver: 'other',
    source_name: null,
    source_uuid: null,
    currency_code: 'UAH',
    statuses_toggle: [],
    distribute_by: [5],
    expense_type_id: null,
    with_expenses: false,
    send_tracking_code: false,
    statuses_tracking_code: [],
    created_at: '2024-05-22T14:14:04.000000Z',
    updated_at: '2024-05-22T14:14:04.000000Z',
    deleted_at: null,
    shop_info: [],
  },
  {
    id: 3,
    name: 'Маріанна',
    alias: 'marianna',
    driver: 'other',
    source_name: null,
    source_uuid: null,
    currency_code: 'UAH',
    statuses_toggle: [],
    distribute_by: [4],
    expense_type_id: null,
    with_expenses: false,
    send_tracking_code: false,
    statuses_tracking_code: [],
    created_at: '2024-05-22T14:14:27.000000Z',
    updated_at: '2024-05-22T14:14:27.000000Z',
    deleted_at: null,
    shop_info: [],
  },
  {
    id: 4,
    name: 'Любов',
    alias: 'lyubov',
    driver: 'other',
    source_name: null,
    source_uuid: null,
    currency_code: 'UAH',
    statuses_toggle: [],
    distribute_by: [6],
    expense_type_id: null,
    with_expenses: false,
    send_tracking_code: false,
    statuses_tracking_code: [],
    created_at: '2024-05-22T14:14:47.000000Z',
    updated_at: '2024-05-22T14:14:47.000000Z',
    deleted_at: null,
    shop_info: [],
  },
  {
    id: 5,
    name: 'Анастасія',
    alias: 'anastasiya',
    driver: 'other',
    source_name: null,
    source_uuid: null,
    currency_code: 'UAH',
    statuses_toggle: [],
    distribute_by: [7],
    expense_type_id: null,
    with_expenses: false,
    send_tracking_code: false,
    statuses_tracking_code: [],
    created_at: '2024-06-02T21:14:01.000000Z',
    updated_at: '2024-06-02T21:14:01.000000Z',
    deleted_at: null,
    shop_info: [],
  },
  {
    id: 6,
    name: 'Оксана',
    alias: 'oksana',
    driver: 'other',
    source_name: null,
    source_uuid: null,
    currency_code: 'UAH',
    statuses_toggle: [],
    distribute_by: [9],
    expense_type_id: null,
    with_expenses: false,
    send_tracking_code: false,
    statuses_tracking_code: [],
    created_at: '2024-06-07T14:48:14.000000Z',
    updated_at: '2024-06-07T14:48:14.000000Z',
    deleted_at: null,
    shop_info: [],
  },
  {
    id: 7,
    name: 'Аліна',
    alias: 'alina',
    driver: 'other',
    source_name: null,
    source_uuid: null,
    currency_code: 'UAH',
    statuses_toggle: [],
    distribute_by: [10],
    expense_type_id: null,
    with_expenses: false,
    send_tracking_code: false,
    statuses_tracking_code: [],
    created_at: '2024-06-30T18:28:38.000000Z',
    updated_at: '2024-06-30T18:33:18.000000Z',
    deleted_at: null,
    shop_info: [],
  },
  {
    id: 8,
    name: 'Олена',
    alias: 'olena',
    driver: 'other',
    source_name: null,
    source_uuid: null,
    currency_code: 'UAH',
    statuses_toggle: [],
    distribute_by: [11],
    expense_type_id: null,
    with_expenses: false,
    send_tracking_code: false,
    statuses_tracking_code: [],
    created_at: '2024-09-30T10:03:42.000000Z',
    updated_at: '2024-09-30T10:08:19.000000Z',
    deleted_at: null,
    shop_info: [],
  },
  {
    id: 9,
    name: 'Соломія',
    alias: 'solomiya',
    driver: 'other',
    source_name: null,
    source_uuid: null,
    currency_code: 'UAH',
    statuses_toggle: [],
    distribute_by: [12],
    expense_type_id: null,
    with_expenses: false,
    send_tracking_code: false,
    statuses_tracking_code: [],
    created_at: '2024-10-02T09:26:20.000000Z',
    updated_at: '2024-10-02T09:26:43.000000Z',
    deleted_at: null,
    shop_info: [],
  },
  {
    id: 10,
    name: "Дар'я",
    alias: 'darya',
    driver: 'other',
    source_name: null,
    source_uuid: null,
    currency_code: 'UAH',
    statuses_toggle: [],
    distribute_by: [13],
    expense_type_id: null,
    with_expenses: false,
    send_tracking_code: false,
    statuses_tracking_code: [],
    created_at: '2024-11-08T10:56:43.000000Z',
    updated_at: '2024-11-08T10:56:43.000000Z',
    deleted_at: null,
    shop_info: [],
  },
  {
    id: 11,
    name: 'Руслана',
    alias: 'ruslana',
    driver: 'other',
    source_name: null,
    source_uuid: null,
    currency_code: 'UAH',
    statuses_toggle: [],
    distribute_by: [14],
    expense_type_id: null,
    with_expenses: false,
    send_tracking_code: false,
    statuses_tracking_code: [],
    created_at: '2025-02-18T22:06:41.000000Z',
    updated_at: '2025-02-18T22:06:41.000000Z',
    deleted_at: null,
    shop_info: [],
  },
  {
    id: 12,
    name: 'Ксенія',
    alias: 'kseniya',
    driver: 'other',
    source_name: null,
    source_uuid: null,
    currency_code: 'UAH',
    statuses_toggle: [],
    distribute_by: [15],
    expense_type_id: null,
    with_expenses: false,
    send_tracking_code: false,
    statuses_tracking_code: [],
    created_at: '2025-02-20T07:02:08.000000Z',
    updated_at: '2025-02-20T07:02:08.000000Z',
    deleted_at: null,
    shop_info: [],
  },
  {
    id: 13,
    name: 'Інстаграм',
    alias: 'instagram',
    driver: 'other',
    source_name: null,
    source_uuid: null,
    currency_code: 'UAH',
    statuses_toggle: [],
    distribute_by: [15],
    expense_type_id: null,
    with_expenses: false,
    send_tracking_code: false,
    statuses_tracking_code: [],
    created_at: '2025-11-06T08:30:02.000000Z',
    updated_at: '2025-11-06T08:30:02.000000Z',
    deleted_at: null,
    shop_info: [],
  },
];

export const ORDER_SOURCES_MAP = ORDER_SOURCES.reduce(
  (acc, source) => {
    acc[source.id] = source;
    return acc;
  },
  {} as Record<number, (typeof ORDER_SOURCES)[number]>,
);
